Task-42687: Implement remove news article
exoplatform/news pull request #101
Opened 2021-04-22 15:07 UTC by azayati

Current behaviour:

- Only delete news article service and rest service is available
- When deleting the news article, the related activities are not removed
- It is not possible to remove a news article from news detail

New behaviour:

- When deleting the news article, the related activities are also removed
- It will be possible to remove a news article from news detail

2021-04-28 07:21 UTC, azayati reviewed
@hassenelkamel-exo See review

2021-04-28 07:21 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsRestResourcesV1.java
> +              LOG.warn("Error deleting an news", e);
```suggestion
              LOG.warn("Error when deleting a news", e);
```

2021-04-28 07:21 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsRestResourcesV1.java
> +      return Response.status(Response.Status.BAD_REQUEST).entity("News identifier must be a positive integer").build();
```suggestion
      return Response.status(Response.Status.BAD_REQUEST).entity("News identifier must not be null or empty").build();
```

2021-04-28 07:21 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsRestResourcesV1.java
> +  @Path("{newsId}/undoDelete")
```suggestion
  @Path("{id}/undoDelete")
```

2021-04-28 07:21 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsRestResourcesV1.java
> +                                    "newsId"
```suggestion
                                    "id"
```

2021-04-28 07:21 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsRestResourcesV1.java
> +                                  @ApiParam(value = "News technical identifier", required = true)
```suggestion
                                  @ApiParam(value = "News node identifier", required = true)
```

2021-04-28 07:21 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsRestResourcesV1.java
> +                     .entity("News id was already deleted or isn't planned to be deleted")
```suggestion
                     .entity("News with id {} was already deleted or isn't planned to be deleted", id)
```

2021-04-28 07:21 UTC, azayati commented on services/src/main/resources/locale/portlet/news/News_en.properties
> +news.undoRemoveActivity=Undo
```suggestion
news.details.undoDelete=Undo
```

2021-04-28 07:21 UTC, azayati commented on services/src/main/resources/locale/portlet/news/News_en.properties
> +news.activityDeleteSuccess=Activity deleted
```suggestion
news.details.deleteSuccess=News deleted
```

2021-04-28 07:21 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsRestResourcesV1.java
> +  @Produces(MediaType.APPLICATION_JSON)
Not needed IMHO, to keep just @Consumes

2021-04-28 07:21 UTC, azayati commented on webapp/src/main/webapp/components/snackbar/ExoNewsNotificationAlerts.vue
> +        const clickMessage = this.$t('news.undoRemoveActivity');
```suggestion
        const clickMessage = this.$t('news.details.undoDelete');
```

2021-04-28 07:21 UTC, azayati commented on webapp/src/main/webapp/components/snackbar/ExoNewsNotificationAlerts.vue
> +        const message = this.$t('news.activityDeleteSuccess');
```suggestion
        const message = this.$t('news.details.deleteSuccess');
```

2021-04-28 07:21 UTC, azayati commented on webapp/src/main/webapp/news-details/components/ExoNewsDetails.vue
> +    reloadNews(newsId) {
For what this function is needed ?

2021-04-28 07:21 UTC, azayati commented on webapp/src/main/webapp/news-details/components/ExoNewsDetails.vue
> +        .then(() => this.$root.$emit('news-deleted', this.news));
you should redirect to homepage after delete success

2021-04-28 07:21 UTC, azayati commented on webapp/src/main/webapp/services/newsServices.js
> +      throw new Error('Error deleting news');
```suggestion
      throw new Error('Error when deleting news with id:' + newsId);
```

2021-04-28 07:21 UTC, azayati commented on webapp/src/main/webapp/services/newsServices.js
> +      throw new Error('Error undoing deleting news');
```suggestion
      throw new Error('Error when undoing deleting news with id:' + newsId);
```

2021-04-28 07:21 UTC, azayati commented on webapp/src/main/webapp/news-details/components/ExoNewsDetailsActionMenu.vue
> +    showDeleteButton: {
showDeleteButton should be false by default, true when the authenticated user is the news author (or space manager to be verified)

2021-04-28 08:15 UTC, hassenelkamel-exo commented on webapp/src/main/webapp/services/newsServices.js
> +      throw new Error('Error deleting news');
with new Error you can only show new Error('String')

2021-04-28 09:11 UTC, hassenelkamel-exo commented on webapp/src/main/webapp/groovy/news/webui/activity/UINewsFullActivity.gtmpl
> +  <% }
<% } %>

2021-04-28 09:12 UTC, hassenelkamel-exo requested changes

2021-04-28 09:12 UTC, hassenelkamel-exo commented on webapp/src/main/webapp/groovy/news/webui/activity/UINewsStreamActivity.gtmpl
> +<% }
<% } %>

2021-04-28 09:12 UTC, hassenelkamel-exo commented on webapp/src/main/webapp/groovy/news/webui/activity/UISharedNewsFullActivity.gtmpl
> +<% }
<% } %>

2021-04-28 09:12 UTC, hassenelkamel-exo commented on webapp/src/main/webapp/groovy/news/webui/activity/UISharedNewsStreamActivity.gtmpl
> +<% }
<% } %>

2021-04-28 09:13 UTC, hassenelkamel-exo requested changes

2021-04-28 09:13 UTC, hassenelkamel-exo commented on webapp/src/main/webapp/groovy/news/webui/activity/UISharedNewsStreamActivity.gtmpl
> +<% }
<% } %>

2021-04-29 08:26 UTC, azayati reviewed
@hassenelkamel-exo see review
Some remarks from the previous review are missed, to be considered

2021-04-29 08:26 UTC, azayati commented on services/src/main/java/org/exoplatform/news/NewsServiceImpl.java
> +    return userACL.isSuperUser() || spaceService.isSuperManager(authenticatedUser) || spaceService.isManager(currentSpace, authenticatedUser);
```suggestion
    return authenticatedUser.equals(posterId) || userACL.isSuperUser() || spaceService.isSuperManager(authenticatedUser) || spaceService.isManager(currentSpace, authenticatedUser);
```

2021-04-29 08:26 UTC, azayati commented on services/src/main/java/org/exoplatform/news/model/News.java
> +  public Boolean getCanDelete() {
```suggestion
  public Boolean isCanDelete() {
```

2021-04-29 08:26 UTC, azayati commented on webapp/src/main/webapp/news-details/main.js
> +                  :show-delete-button="showEditButton"/>`,
```suggestion
                  :show-delete-button="showDeleteButton"/>`,
```

2021-04-29 08:26 UTC, azayati commented on webapp/src/main/webapp/news-details/components/ExoNewsDetails.vue
> +      default: true
```suggestion
      default: false
```

2021-04-29 08:52 UTC, hassenelkamel-exo approved these changes, later dismissed

2021-04-29 09:24 UTC, azayati reviewed
LGTM after QA validation

2021-04-29 09:42 UTC, hassenelkamel-exo approved these changes, later dismissed

2021-04-30 07:41 UTC, hassenelkamel-exo approved these changes

2021-04-30 07:45 UTC, merged