feat: Implement create news draft article - EXO-69636
exoplatform/news pull request #1140
Opened 2024-03-15 10:49 UTC by sofyenne

2024-03-15 11:41 UTC, azayati requested changes

2024-03-15 11:41 UTC, azayati commented on services/src/main/java/org/exoplatform/news/service/impl/NewsServiceImplV2.java
> +  private static final Log         LOG                             = ExoLogger.getLogger(NewsServiceImpl.class);
```suggestion
  private static final Log         LOG                             = ExoLogger.getLogger(NewsServiceImplV2.class);
```

2024-03-15 11:41 UTC, azayati commented on services/src/main/java/org/exoplatform/news/service/impl/NewsServiceImplV2.java
> +  public static final String       ARTICLES_ROOT_PAGE_NAME         = "Articles";
```suggestion
  public static final String       NEWS_ARTICLES_ROOT_NOTE_PAGE_NAME         = "Articles";
```

2024-03-18 09:40 UTC, azayati requested changes

2024-03-18 09:40 UTC, azayati commented on services/src/main/java/org/exoplatform/news/service/impl/NewsServiceImplV2.java
> +        properties.put("illustrationId", illustrationId >= 0 ? String.valueOf(illustrationId) : null);
- define constants for "summary", "illustrationId"
- "uploadId" and "publicationState" not needed IMO at this step

2024-03-18 09:40 UTC, azayati commented on services/src/main/java/org/exoplatform/news/service/impl/NewsServiceImplV2.java
> +        MetadataKey newsDraftMetadataKey = new MetadataKey(METADATA_TYPE.getName(), "news", 0);
```suggestion
        MetadataKey newsDraftMetadataKey = new MetadataKey(NEWS_METADATA_TYPE.getName(), "news", 0);
```
define a constant NEWS_METADATA_NAME for "news"

2024-03-18 09:40 UTC, azayati commented on services/src/main/java/org/exoplatform/news/service/impl/NewsServiceImplV2.java
> +    throw new EntityNotFoundException("Parent note not found");
```suggestion
    throw new EntityNotFoundException("News articles root note parent not found");
```

2024-03-18 09:40 UTC, azayati commented on services/src/main/java/org/exoplatform/news/service/impl/NewsServiceImplV2.java
> +                                       FILE_API_NAME_SPACE,
```suggestion
                                       FILE_API_NAME_SPACE,
```
define a namespace for news

2024-03-18 09:40 UTC, azayati commented on services/src/test/java/org/exoplatform/news/service/impl/NewsServiceImplV2Test.java
> +package org.exoplatform.news.service.impl;
add header

2024-03-18 10:18 UTC, sofyenne commented on services/src/main/java/org/exoplatform/news/service/impl/NewsServiceImplV2.java
> +        properties.put("illustrationId", illustrationId >= 0 ? String.valueOf(illustrationId) : null);
done!

2024-03-18 10:37 UTC, azayati approved these changes
LGTM

2024-03-18 10:39 UTC, merged