Task-46057: Implement digest mail for news notifications
exoplatform/news pull request #172
Opened 2021-07-01 07:37 UTC by AzmiTouil

2021-07-01 13:48 UTC, azayati requested changes
See review

2021-07-01 13:48 UTC, azayati commented on services/src/main/java/org/exoplatform/news/notification/provider/MailTemplateProvider.java
> +        sb.append("<li style=\"margin: 0 0 13px 14px; font-size: 13px; line-height: 18px; font-family: HelveticaNeue, Helvetica, Arial, sans-serif;\">");
Why we inject the html here ?

2021-07-01 13:48 UTC, azayati commented on services/src/main/resources/locale/portlet/news/News_en.properties
> +Notification.digest.one.PostNewsNotificationPlugin=$USER <span style="color:#333333">have posted</span> $CONTENT_TITLE <span style="color:#333333">in</span> $SPACE_TITLE.
Why we inject the html here ?

2021-07-01 16:22 UTC, azayati approved these changes, later dismissed
LGTM after QA validation

2021-07-02 12:31 UTC, rdenarie commented on services/src/main/java/org/exoplatform/news/notification/provider/MailTemplateProvider.java
> +        List<NotificationInfo> notificationInfos = map.get(notification.getKey());
Instead of calling map, you should have something link 
notification.getValue()

2021-07-05 09:07 UTC, azayati approved these changes
LGTM

2021-07-05 09:12 UTC, merged