Task-45890: Scheduling drawer permissions
exoplatform/news pull request #183
Opened 2021-07-09 08:24 UTC by hassenelkamel-exo

2021-07-13 13:39 UTC, azayati requested changes
See review

2021-07-13 13:39 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsRestResourcesV1.java
> +    return ((spaceHasARedactor && (isRedactor || isManager)) || (!spaceHasARedactor && isManager));
```suggestion
    return spaceService.isManager(space, authenticatedUser) || spaceService.isRedactor(space, authenticatedUser);
```

2021-07-13 13:39 UTC, azayati commented on services/src/main/resources/locale/portlet/news/News_en.properties
> +news.composer.chooseNotPost=Choose when you no longer want to publish your article.
```suggestion
news.composer.chooseNotPost=Choose when you no longer want to post your article.
```

2021-07-13 13:39 UTC, azayati commented on webapp/src/main/webapp/schedule-news/components/ExoScheduleNewsDrawer.vue
> +      return this.postArticleMode==='later' ? this.$t('news.composer.schedule'): this.$t('news.composer.post');
```suggestion
      return this.postArticleMode === 'later' ? this.$t('news.composer.schedule'): this.$t('news.composer.post');
```

2021-07-13 13:39 UTC, azayati commented on webapp/src/main/webapp/schedule-news/components/ExoScheduleNewsDrawer.vue
> +        this.disabled = false;
Is the disable considered ?

2021-07-13 13:39 UTC, azayati commented on webapp/src/main/webapp/schedule-news/main.js
> +let shareNewsApp;
```suggestion
let scheduleNewsDrawer
```
?

2021-07-13 13:39 UTC, azayati commented on webapp/webpack.common.js
> +    scheduleNewsDrawer: './src/main/webapp/schedule-news/main.js',
```suggestion
    scheduleNewsDrawer: './src/main/webapp/schedule-news-drawer/main.js',
```

2021-07-13 16:30 UTC, azayati submitted a review, later dismissed
LGTM after QA validation

2021-07-19 08:27 UTC, ahamdi approved these changes, later dismissed

2021-07-19 08:27 UTC, ahamdi commented on services/src/main/java/org/exoplatform/news/rest/NewsRestResourcesV1.java
> +  @ApiResponses(value = { @ApiResponse(code = 200, message = "News created"),
```suggestion
  @ApiResponses(value = { @ApiResponse(code = 200, message = "User ability to create a news is returned"),
```

2021-07-19 08:27 UTC, ahamdi commented on services/src/main/java/org/exoplatform/news/rest/NewsRestResourcesV1.java
> +  @ApiResponses(value = { @ApiResponse(code = 200, message = "News scheduled"),
```suggestion
  @ApiResponses(value = { @ApiResponse(code = 200, message = "User ability to schedule a news"),
```

2021-07-19 08:27 UTC, ahamdi commented on webapp/src/main/webapp/schedule-news-drawer/components/ExoScheduleNewsDrawer.vue
> +      }
Could be simplified by
```suggestion
        this.disabled = postDate.getTime() === scheduleDate.getTime();
```

2021-07-22 09:10 UTC, ahamdi approved these changes

2021-07-22 09:30 UTC, merged