Task-49004_49006_49602: Change the UI of the posting drawer for publishers
exoplatform/news pull request #303
Opened 2021-10-06 17:00 UTC by hassenelkamel-exo

Prior to this change, we used a simple drawer to post news. After this enhancement, we implement a stepper which contains these steps: 
- Step 1: Post or not on the stream
- Step 2: Publish in a targeted section which is disabled with a feature flag until finishing the feature
- Step 3: Schedule (keep the old behavior)

2021-10-12 14:34 UTC, azayati requested changes
See review

2021-10-12 14:34 UTC, azayati commented on webapp/src/main/webapp/skin/less/news.less
> +    width: 95%;
to be tested on mobile

2021-10-12 14:34 UTC, azayati commented on webapp/src/main/webapp/WEB-INF/conf/news/news-configuration.xml
> +    <key>TargetingNewsFeatureProperties</key>
```suggestion
    <key>NewsPublishTargetingFeatureProperties</key>
```

2021-10-12 14:34 UTC, azayati commented on webapp/src/main/webapp/WEB-INF/conf/news/news-configuration.xml
> +        <name>TargetingNewsFeatureProperties</name>
```suggestion
        <name>NewsPublishTargetingFeatureProperties</name>
```

2021-10-12 14:34 UTC, azayati commented on webapp/src/main/webapp/WEB-INF/conf/news/news-configuration.xml
> +        <description>News targeting Feature enablement flag</description>
```suggestion
        <description>News publish targeting Feature enablement flag</description>
```

2021-10-12 14:34 UTC, azayati commented on webapp/src/main/webapp/WEB-INF/conf/news/news-configuration.xml
> +        <property name="exo.feature.news.targetingPublish.enabled" value="${exo.feature.news.targetingPublish.enabled:false}" />
```suggestion
        <property name="exo.feature.news.publishTargeting.enabled" value="${exo.feature.news.publishTargeting.enabled:false}" />
```

2021-10-12 14:34 UTC, azayati commented on webapp/src/main/webapp/news-details/components/ExoNewsDetailsBody.vue
> +                    <div v-else-if="updatedDate" class="newsInformationValue newsUpdatedDate">{{ updatedDate }}</div>
why this modification ?

2021-10-12 14:34 UTC, azayati commented on webapp/src/main/webapp/schedule-news-drawer/components/ExoScheduleNewsDrawer.vue
> +            {{ $t('news.composer.stepper.postStream') }}
```suggestion
            {{ $t('news.composer.stepper.postOnStream.title') }}
```

2021-10-12 14:34 UTC, azayati commented on webapp/src/main/webapp/schedule-news-drawer/components/ExoScheduleNewsDrawer.vue
> +              <div class="d-flex flex-row grey--text ms-2 chooseSpaceStream">{{ $t('news.composer.stepper.chooseStream') }}</div>
```suggestion
              <div class="d-flex flex-row grey--text ms-2 postOnStreamOption">{{ $t('news.composer.stepper.postOnStream.option') }}</div>
```

2021-10-12 14:34 UTC, azayati commented on webapp/src/main/webapp/schedule-news-drawer/components/ExoScheduleNewsDrawer.vue
> +                  {{ $t('news.composer.stepper.postActivityStream') }}
```suggestion
                  {{ $t('news.composer.stepper.postOnStream.description') }}
```

2021-10-12 14:34 UTC, azayati commented on webapp/src/main/webapp/schedule-news-drawer/components/ExoScheduleNewsDrawer.vue
> +            {{ $t('news.composer.stepper.publishSection') }}
```suggestion
            {{ $t('news.composer.stepper.publishSection.title') }}
```

2021-10-12 14:34 UTC, azayati commented on webapp/src/main/webapp/schedule-news-drawer/components/ExoScheduleNewsDrawer.vue
> +              <div class="d-flex flex-row grey--text ms-2">{{ $t('news.composer.stepper.publishDedicatedSection') }}</div>
```suggestion
              <div class="d-flex flex-row grey--text ms-2">{{ $t('news.composer.stepper.publishSection.description') }}</div>
```

2021-10-12 14:34 UTC, azayati commented on webapp/src/main/webapp/schedule-news-drawer/components/ExoScheduleNewsDrawer.vue
> +              <div v-if="allowTargetingPublish" class="d-flex flex-row grey--text ms-2">{{ $t('news.composer.stepper.selectedTarget') }}</div>
```suggestion
              <div v-if="allowPublishTargeting" class="d-flex flex-row grey--text ms-2">{{ $t('news.composer.stepper.selectedTarget.description') }}</div>
```

2021-10-12 14:34 UTC, azayati commented on webapp/src/main/webapp/schedule-news-drawer/components/ExoScheduleNewsDrawer.vue
> +                  :placeholder="$t('news.composer.stepper.chooseTarget')"
```suggestion
                  :placeholder="$t('news.composer.stepper.chooseTargets.option)"
```

2021-10-12 14:34 UTC, azayati commented on webapp/src/main/webapp/schedule-news-drawer/components/ExoScheduleNewsDrawer.vue
> +                  ref="selectTarget"
```suggestion
                  id="chooseTargets"
                  ref="chooseTargets"
```

2021-10-12 15:40 UTC, hassenelkamel-exo commented on webapp/src/main/webapp/skin/less/news.less
> +    width: 95%;
well tested in mobile view

2021-10-12 15:48 UTC, hassenelkamel-exo commented on webapp/src/main/webapp/news-details/components/ExoNewsDetailsBody.vue
> +                    <div v-else-if="updatedDate" class="newsInformationValue newsUpdatedDate">{{ updatedDate }}</div>
some times when reload details we have null value so we use `updatedDate` computed value

2021-10-13 10:34 UTC, azayati requested changes
see review

2021-10-13 10:34 UTC, azayati commented on webapp/src/main/webapp/schedule-news-drawer/components/ExoScheduleNewsDrawer.vue
> +              <div class="d-flex flex-row grey--text ms-2 postOnStreamOption">{{ $t('news.composer.stepper.postOnStream.option') }}</div>
```suggestion
              <div class="d-flex flex-row grey--text ms-2 postOnStreamOption">{{ $t('news.composer.stepper.postOnStream.description') }}</div>
```

2021-10-13 10:34 UTC, azayati commented on webapp/src/main/webapp/schedule-news-drawer/components/ExoScheduleNewsDrawer.vue
> +                  {{ $t('news.composer.stepper.postOnStream.description') }}
```suggestion
                  {{ $t('news.composer.stepper.postOnStream.option') }}
```

2021-10-13 10:34 UTC, azayati commented on webapp/src/main/webapp/schedule-news-drawer/components/ExoScheduleNewsDrawer.vue
> +                  {{ $t('news.details.header.menu.publish') }}
```suggestion
                  {{ $t('news.composer.publishSection.option') }}
```

2021-10-13 10:34 UTC, azayati commented on webapp/src/main/webapp/schedule-news-drawer/components/ExoScheduleNewsDrawer.vue
> +            {{ $t('news.composer.schedule') }}
```suggestion
            {{ $t(news.composer.stepper.schedule.title') }}
```

2021-10-13 11:33 UTC, azayati submitted a review, later dismissed
LGTM after QA validation

2021-10-14 16:39 UTC, azayati approved these changes
LGTM

2021-10-14 16:40 UTC, merged