Task-49720:  Add the possibility to Post or not Post on the stream
exoplatform/news pull request #313
Opened 2021-10-20 12:12 UTC by hassenelkamel-exo

Prior to this change, when we post an article, a news activity is generated automatically. After this change,, we add the possibility to choose the generated news activity is posted or not posted on the stream. When we choose to not post, the generated activity is hidden.

2021-10-20 17:18 UTC, azayati requested changes
See review
Keep only modifications related to post/don't post on the stream

2021-10-20 17:18 UTC, azayati commented on services/src/main/java/org/exoplatform/news/NewsServiceImpl.java
> +    templateParams.put("isHiddenActivity", String.valueOf(news.isHiddenActivity()));
we don't need that IMO

2021-10-21 08:08 UTC, hassenelkamel-exo commented on services/src/main/java/org/exoplatform/news/NewsServiceImpl.java
> +    templateParams.put("isHiddenActivity", String.valueOf(news.isHiddenActivity()));
yes i will remove it

2021-10-21 10:20 UTC, azayati requested changes
See review

2021-10-21 10:20 UTC, azayati commented on webapp/src/main/webapp/schedule-news-drawer/components/ExoScheduleNewsDrawer.vue
> +      return (this.postArticleMode === 'immediate' ? false : this.postArticleMode === 'later' && postDate.getTime() === scheduleDate.getTime()) && this.selected === this.publish || this.stepper<3;
```suggestion
      return (this.postArticleMode === 'immediate' ? false : this.postArticleMode === 'later' && postDate.getTime() === scheduleDate.getTime()) && this.selected === this.publish || this.stepper < 3;
```

2021-10-21 10:44 UTC, azayati approved these changes
LGTM after QA validation

2021-10-21 13:50 UTC, merged