Task-49005:Add the possibility to choose a target from the edit scheduling drawer
exoplatform/news pull request #316
Opened 2021-10-21 16:49 UTC by hassenelkamel-exo

2021-10-26 10:00 UTC, azayati requested changes
See review

2021-10-26 10:00 UTC, azayati commented on services/src/main/java/org/exoplatform/news/NewsServiceImpl.java
> +  public static final String       NEWS_ACTIVITY_VISIBILITY_MIXIN_TYPE = "mix:activityVisibility";
```suggestion
  public static final String       NEWS_ACTIVITY_VISIBILITY_MIXIN_TYPE = "mix:newsPosting";
```

2021-10-26 10:00 UTC, azayati commented on services/src/main/java/org/exoplatform/news/NewsServiceImpl.java
> +  public static final String       NEWS_ACTIVITY_HIDDEN_MIXIN_PROP     = "exo:isHiddenActivity";
```suggestion
  public static final String       NEWS_ACTIVITY_HIDDEN_MIXIN_PROP     = "exo:newsPosted";
```

2021-10-26 10:00 UTC, azayati commented on services/src/main/java/org/exoplatform/news/NewsServiceImpl.java
> +      news.setHiddenActivity(Boolean.valueOf(node.getProperty(NEWS_ACTIVITY_HIDDEN_MIXIN_PROP).getString()));
```suggestion
      news.setPosted(Boolean.valueOf(node.getProperty(NEWS_ACTIVITY_HIDDEN_MIXIN_PROP).getString()));
```

2021-10-26 10:00 UTC, azayati commented on services/src/main/java/org/exoplatform/news/NewsServiceImpl.java
> +      news.setHiddenActivity(false);
```suggestion
      news.setPosted(false);
```

2021-10-26 10:00 UTC, azayati commented on services/src/main/java/org/exoplatform/news/NewsServiceImpl.java
> +  public boolean canChooseTargets(String authenticatedUser) {
this should be the same as canPublishNews, why adding that ?

2021-10-26 10:00 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsRestResourcesV1.java
> +  public Response canChooseTargets(@Context HttpServletRequest request) {
this should be the same as canPublishNews, why adding that ?

2021-10-26 10:00 UTC, azayati commented on services/src/main/resources/locale/portlet/news/News_en.properties
> +news.composer.stepper.chooseTarget.mandatory=* The targets selector is mandatory
```suggestion
news.composer.stepper.chooseTarget.mandatory=The targets selector is mandatory
```
add the * directly in vue file

2021-10-26 12:02 UTC, azayati requested changes
see review

2021-10-26 12:02 UTC, azayati commented on services/src/main/java/org/exoplatform/news/NewsServiceImpl.java
> +  public static final String       NEWS_ACTIVITY_VISIBILITY_MIXIN_TYPE = "mix:newsActivityPosting";
```suggestion
  public static final String       NEWS_ACTIVITY_POSTING_MIXIN_TYPE = "mix:newsActivityPosting";
```

2021-10-26 12:02 UTC, azayati commented on services/src/main/java/org/exoplatform/news/NewsServiceImpl.java
> +  public static final String       NEWS_ACTIVITY_HIDDEN_MIXIN_PROP     = "exo:newsActivityPosted";
```suggestion
  public static final String       NEWS_ACTIVITY_POSTED_MIXIN_PROP     = "exo:newsActivityPosted";
```

2021-10-26 12:02 UTC, azayati commented on webapp/src/main/webapp/schedule-news-drawer/components/ExoScheduleNewsDrawer.vue
> +        <div v-else>
this part should be for simple redactors or managers in order to juste post/don't post and schedule

2021-10-26 12:02 UTC, azayati commented on services/src/main/java/org/exoplatform/news/NewsServiceImpl.java
> +      if (scheduledNewsNode.canAddMixin(NEWS_ACTIVITY_VISIBILITY_MIXIN_TYPE)
should we store this information also when posting immediately ?

2021-10-26 12:15 UTC, hassenelkamel-exo commented on webapp/src/main/webapp/schedule-news-drawer/components/ExoScheduleNewsDrawer.vue
> +        <div v-else>
yes

2021-10-26 13:17 UTC, hassenelkamel-exo commented on services/src/main/java/org/exoplatform/news/NewsServiceImpl.java
> +      if (scheduledNewsNode.canAddMixin(NEWS_ACTIVITY_VISIBILITY_MIXIN_TYPE)
yes, we need it when we use the edit publishing drawer

2021-10-26 13:35 UTC, hassenelkamel-exo commented on services/src/main/resources/locale/portlet/news/News_en.properties
> +news.composer.stepper.chooseTarget.mandatory=* The targets selector is mandatory
IMO, If we put it in vue composant, anyone can think that is unintentionally made.

2021-10-26 14:19 UTC, azayati requested changes
See review

2021-10-26 14:19 UTC, azayati commented on services/src/main/resources/locale/portlet/news/News_en.properties
> +news.composer.stepper.chooseTarget.mandatory=* The targets selector is mandatory
no I don't think so, the asterisk should not be part of translation

2021-10-26 14:19 UTC, azayati commented on webapp/src/main/webapp/schedule-news-drawer/components/ExoScheduleNewsDrawer.vue
> +          <div v-if="canPublishNews" class="d-flex flex-column mt-4 ms-3">
this part should be deleted

2021-10-27 11:26 UTC, azayati submitted a review, later dismissed
LGTM after QA validation

2021-10-28 09:37 UTC, azayati approved these changes
LGTM

2021-10-28 09:38 UTC, merged