Task-50569: Resume the possibility to center the text on CkEditor
exoplatform/news pull request #323
Opened 2021-10-27 15:54 UTC by ahmadmido

2021-10-27 17:14 UTC, azayati requested changes
see review

2021-10-27 17:14 UTC, azayati commented on webapp/src/main/webapp/news-activity-composer-app/components/ExoNewsActivityComposer.vue
> -            attachFileButton.appendChild(spanBadge);
you should adapt them to the new ids, cc @hassenelkamel-exo 
To be verified and tested also the ids here https://github.com/exoplatform/news/pull/323/files#diff-22f9ace050d5a5d8e0e892116084dea8d84f4658621d15a49d7b66596bc161e3L982-L1009

2021-10-28 10:49 UTC, azayati approved these changes
LGTM

2021-10-28 10:52 UTC, hassenelkamel-exo approved these changes
LGTM

2021-10-28 10:52 UTC, hassenelkamel-exo commented on webapp/src/main/webapp/news-activity-composer-app/components/ExoNewsActivityComposer.vue
> -            attachFileButton.appendChild(spanBadge);
you should put it in the code block of mobile

2021-10-28 14:06 UTC, merged