TASK-51421: Bookmark/unbookmark a news
exoplatform/news pull request #357
Opened 2021-11-25 15:58 UTC by aelbenney

2021-11-25 16:12 UTC, nidhalnidhal approved these changes

2021-11-26 08:15 UTC, azayati requested changes
We have a big refactoring in progress, please don't merge anything on develop before merging the refactoring

2021-11-26 08:18 UTC, azayati requested changes
See review

2021-11-26 08:18 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsRestResourcesV1.java
> +  public static Map<String, List<MetadataItemEntity>> retrieveMetadataItems(News news,
We should not call directly Metadata service from rest layer neither from service layer.
Rest layer should call service layer and service layer should call favorite service

2021-11-26 13:28 UTC, merged