Task-50876: Add delete target from administration table
exoplatform/news pull request #414
Opened 2022-01-14 17:05 UTC by hassenelkamel-exo

2022-01-17 15:59 UTC, azayati requested changes
see review

2022-01-17 15:59 UTC, azayati commented on services/src/test/java/org/exoplatform/news/NewsTargetingImplTest.java
> +
Implement UT for deleteTargetByName method

2022-01-17 15:59 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsTargetingRestResourcesV1.java
> +    } catch (Exception e) {
you need to catch IllegalAccessException and return Response.Status.UNAUTHORIZED, see NewsRestResourcesV1 methods

2022-01-17 15:59 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsTargetingRestResourcesV1.java
> +      LOG.warn("Error when deleting the news target");
```suggestion
      LOG.error("Error when deleting the news target with name " + targetName, e);
```

2022-01-17 15:59 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsTargetingRestResourcesV1.java
> +              LOG.warn("Error when deleting the news target with name " + targetName, e);
```suggestion
              LOG.error("Error when deleting the news target with name " + targetName, e);
```

2022-01-17 15:59 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsTargetingRestResourcesV1.java
> +  public Response deleteTargetByName(@Context HttpServletRequest request,
```suggestion
  public Response deleteTarget(@Context HttpServletRequest request,
```

2022-01-17 15:59 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsTargetingRestResourcesV1.java
> +  public Response undoDeleteNewsTarget(@Context HttpServletRequest request,
```suggestion
  public Response undoDeleteTarget(@Context HttpServletRequest request,
```

2022-01-17 15:59 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsTargetingRestResourcesV1.java
> +  @Path("{targetName}/undoDeleteNewsTarget")
```suggestion
  @Path("{targetName}/undoDelete")
```

2022-01-17 15:59 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsTargetingRestResourcesV1.java
> +          value = "Undo deleting target news if not yet effectively deleted.",
```suggestion
          value = "Undo deleting news target if not yet effectively deleted.",
```

2022-01-17 15:59 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsTargetingRestResourcesV1.java
> +  @ApiOperation(value = "Delete target news", httpMethod = "DELETE", response = Response.class, notes = "This deletes the target news", consumes = "application/json")
```suggestion
  @ApiOperation(value = "Delete news target", httpMethod = "DELETE", response = Response.class, notes = "This deletes the target news", consumes = "application/json")
```

2022-01-17 15:59 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsTargetingRestResourcesV1.java
> +                  @ApiResponse(code = HTTPStatus.NO_CONTENT, message = "Request fulfilled"),
useless

2022-01-17 15:59 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsTargetingRestResourcesV1.java
> +          @ApiResponse(code = 400, message = "Invalid query input"),
```suggestion
          @ApiResponse(code = HTTPStatus.BAD_REQUEST, message = "Invalid query input"),
```

2022-01-17 15:59 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsTargetingRestResourcesV1.java
> +          @ApiResponse(code = 401, message = "User not authorized to delete the news target"),
```suggestion
          @ApiResponse(code = HTTPStatus.UNAUTHORIZED, message = "User not authorized to delete the news target"),
```

2022-01-17 15:59 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsTargetingRestResourcesV1.java
> +          @ApiResponse(code = 500, message = "Internal server error") })
```suggestion
          @ApiResponse(code = HTTPStatus.INTERNAL_ERROR, message = "Internal server error") })
```

2022-01-17 16:31 UTC, hassenelkamel-exo commented on services/src/main/java/org/exoplatform/news/rest/NewsTargetingRestResourcesV1.java
> +    } catch (Exception e) {
Exception 'java.lang.IllegalAccessException' is never thrown in the corresponding try block

2022-01-24 09:58 UTC, azayati requested changes
See review

2022-01-24 09:58 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsTargetingRestResourcesV1.java
> +            } catch (Exception e) {
You should catch the illegalArgument exception here

2022-01-24 12:37 UTC, azayati requested changes
see review

2022-01-24 12:37 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsTargetingRestResourcesV1.java
> +              LOG.error("Error when deleting the news target with name " + targetName, e);
```suggestion
              LOG.warn("User '{}' is not autorized to delete the news target with name " + targetName, e);
              return Response.status(Response.Status.UNAUTHORIZED).entity(e.getMessage()).build();
```

2022-01-24 12:37 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsTargetingRestResourcesV1.java
> +                     .entity("Target News with name {} was already deleted or isn't planned to be deleted" + targetName)
```suggestion
                     .entity("News target with name {} was already deleted or isn't planned to be deleted" + targetName)
```

2022-01-24 12:37 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsTargetingRestResourcesV1.java
> +  @ApiOperation(value = "Delete news target", httpMethod = "DELETE", response = Response.class, notes = "This deletes the target news", consumes = "application/json")
```suggestion
  @ApiOperation(value = "Delete news target", httpMethod = "DELETE", response = Response.class, notes = "This deletes the news target", consumes = "application/json")
```

2022-01-24 12:37 UTC, azayati commented on services/src/main/java/org/exoplatform/news/service/impl/NewsTargetingServiceImpl.java
> +      throw new IllegalArgumentException("User " + currentIdentity.getUserId() + " not authorized to publish news");
```suggestion
      throw new IllegalArgumentException("User " + currentIdentity.getUserId() + " not authorized to delete news target with name " + targetName");
```

2022-01-24 13:23 UTC, azayati requested changes
see review

2022-01-24 13:23 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsTargetingRestResourcesV1.java
> +    } catch (IllegalAccessException e) {
not needed already catched above

2022-01-26 09:56 UTC, azayati approved these changes
LGTM

2022-01-26 09:57 UTC, merged