Task-50800: implement edit target service
exoplatform/news pull request #432
Opened 2022-01-28 17:24 UTC by hassenelkamel-exo

2022-02-07 15:06 UTC, azayati requested changes
see review

2022-02-07 15:06 UTC, azayati commented on services/src/main/java/org/exoplatform/news/service/NewsTargetingService.java
> +   * Update news Metadata by it name
```suggestion
   * Update news target
```

2022-02-07 15:06 UTC, azayati commented on services/src/main/resources/locale/portlet/news/News_en.properties
> +news.publishTargets.managementDrawer.sameNewsTargetWarning=A target with the same name already exists.
not changes, revert this

2022-02-07 15:06 UTC, azayati commented on webapp/src/main/webapp/news-list-view/components/settings/NewsSettingsDrawer.vue
> +      return this.targetName && !this.targetName.trim().match(/^[\w\-\s]+$/) && this.targetName.length > 0 ? this.$t('news.list.settings.name.errorMessage') : '';
this modification is a part of develop one https://github.com/exoplatform/news/commit/2c66a5445554b672c7426a42eda0ff810d026242#diff-7853b826a9d2c891b72fcf7bb148c5fde29d6335e95dc4c3a64b1cae755ccab2R104, so to be reverted

2022-02-07 15:06 UTC, azayati commented on webapp/src/main/webapp/services/newsTargetingService.js
> +      throw new Error('Error updating news target');
```suggestion
      throw new Error('Error when updating news target');
```

2022-02-07 15:06 UTC, azayati commented on services/src/main/java/org/exoplatform/news/rest/NewsTargetingRestResourcesV1.java
> +                                   @QueryParam("originalTargetName") String originalTargetName) {
PathParam is better IMO

2022-02-07 16:22 UTC, hassenelkamel-exo commented on webapp/src/main/webapp/news-list-view/components/settings/NewsSettingsDrawer.vue
> +      return this.targetName && !this.targetName.trim().match(/^[\w\-\s]+$/) && this.targetName.length > 0 ? this.$t('news.list.settings.name.errorMessage') : '';
not the same file, in order to optimize code we add it

2022-02-08 11:44 UTC, azayati submitted a review, later dismissed
LGTM after QA validation

2022-02-08 17:37 UTC, azayati approved these changes, later dismissed
LGTM

2022-02-08 18:16 UTC, azayati approved these changes
LGTM

2022-02-08 18:28 UTC, merged