Backport Maint-27977
exoplatform/news pull request #49
Opened 2020-10-02 16:30 UTC by Jihed525

2020-10-02 16:54 UTC, azayati requested changes
See review

2020-10-02 16:54 UTC, azayati commented on upgrade-plugin/pom.xml
> +  </parent>
```suggestion
<parent>
    <artifactId>news</artifactId>
    <groupId>org.exoplatform.addons.news</groupId>
    <version>1.1.x-SNAPSHOT</version>
  </parent>
```

2020-10-02 16:54 UTC, azayati commented on upgrade-plugin/pom.xml
> +  <artifactId>data-upgrade-news</artifactId>
```suggestion
  <artifactId>news-upgrade-plugin</artifactId>
```

2020-10-02 16:54 UTC, azayati commented on upgrade-plugin/pom.xml
> +  <name>eXo Add-on:: Data Upgrade Add-on - NEWS</name>
```suggestion
  <name>eXo Add-on :: NEWS Add-on Upgrade Plugin</name>
```

2020-10-02 16:55 UTC, azayati requested changes
https://github.com/exoplatform/news/pull/42 this PR should be backported also

2020-10-05 10:06 UTC, azayati requested changes
See review

2020-10-05 10:06 UTC, azayati commented on upgrade-plugin/src/main/resources/conf/portal/configuration.xml
> +          <value>6.0.0</value>
Should be 5.3.5

2020-10-05 10:37 UTC, Jihed525 commented on upgrade-plugin/src/main/resources/conf/portal/configuration.xml
> +          <value>6.0.0</value>
done

2020-10-06 16:01 UTC, azayati approved these changes
LGTM

2020-10-06 16:09 UTC, merged