MAINT-40063 : fix news formatMention when no text after @ char
exoplatform/news pull request #63
Opened 2021-01-27 16:53 UTC by hakermi

2021-01-27 16:59 UTC, ahamdi requested changes
Please add :
 - description to the PR
 - A Unity Test to cover the fix and prove it does no more happen

2021-01-27 16:59 UTC, ahamdi commented on services/src/main/java/org/exoplatform/news/NewsServiceImpl.java
> +            next = next.split("@")[0] + "<a href=\"" + CommonsUtils.getCurrentDomain() + identity.getProfile().getUrl() + "\">"
```suggestion
        String[] splitTable = next.split("@");
        if (splitTable.length > 1) {
          username = splitTable[1];
          org.exoplatform.social.core.identity.model.Identity identity = loadUser(username);
          if (identity != null) {
            next = splitTable[0] + "<a href=\"" + CommonsUtils.getCurrentDomain() + identity.getProfile().getUrl() + "\">"
```

2021-01-27 16:59 UTC, plamarque reviewed
unit tests covering the cases handled by the change seem missing.

2021-01-27 19:01 UTC, hakermi commented
> Please add :
> 
> * description to the PR
> * A Unit Test to cover the fix and prove it does no more happen

2021-01-28 11:24 UTC, ahamdi commented on services/src/main/java/org/exoplatform/news/NewsServiceImpl.java
> +          username = splitTable[1];
```suggestion
        String[] splitTable = next.split("@");
        if (splitTable.length > 1) {
          username = splitTable[1];
```

2021-01-28 11:26 UTC, ahamdi submitted a review, later dismissed

2021-01-28 13:18 UTC, ahamdi approved these changes

2021-01-28 13:19 UTC, merged