TASK-39258: Add notification when being mentioned in an article (#69)
exoplatform/news pull request #76
Opened 2021-02-16 12:06 UTC by mzorai

2021-02-16 13:11 UTC, ahamdi requested changes
This should be refactored to follow the PR proposed here https://github.com/exoplatform/news/pull/73

2021-02-17 09:49 UTC, mzorai commented
> This should be refactored to follow the PR proposed here #73

cc @aelbenney could you please help in this

2021-02-18 09:38 UTC, aelbenney approved these changes, later dismissed

2021-02-18 09:51 UTC, ahamdi requested changes

2021-02-18 09:51 UTC, ahamdi commented on services/src/main/java/org/exoplatform/news/NewsUtils.java
> +  public static News formatNews(News news) {
This function  is no more needed I think

2021-02-18 11:41 UTC, ahamdi approved these changes

2021-02-18 11:41 UTC, merged