fix: searching on news app by the news tag text - EXO-64009
exoplatform/news pull request #850
Opened 2023-05-03 11:16 UTC by sofyenne

Before to this change on news app when we searched for news by typing the text of the tag, no results were displayed. The issue was that the news query was not built to include the filter by the tag text.

This change will update the build query method to enable filtering by the tag text.

2023-05-03 21:52 UTC, ahamdi requested changes

2023-05-03 21:52 UTC, ahamdi commented on services/src/main/java/org/exoplatform/news/connector/NewsSearchConnector.java
> +      if (filter.getSearchText().split(" ").length <= 1){
We need to be sure if the text is a tag or a simple text, we can not guess it based on the number of words in the query

2023-05-04 13:07 UTC, sofyenne commented on services/src/main/java/org/exoplatform/news/connector/NewsSearchConnector.java
> +      if (filter.getSearchText().split(" ").length <= 1){
done ! Using tag service we will find the tag names based on the search text to ensure that the search text is a tag text .

2023-05-05 10:37 UTC, ahamdi approved these changes

2023-05-05 10:46 UTC, merged