fix: Article drafts edition makes the article displayed on top of the news app - EXO-56012
exoplatform/news pull request #956
Opened 2023-11-01 09:20 UTC by akhanfir

Before this fix, when post several articles in a space and in news app, click on three dots>edit button for the last posted article then type some inputs then click on cancel, this article is displayed on the top of the posted articles list. in fact, it is that the draft which was created and the article existing in the same property of the date modified (dateModified) to fix this problem, during creation of article in set another property (publication:liveDate) and during get all the articles by modifying the tree property according to the filter of this list if it is drafted by using it as a property (exo:dateModified) otherwise using the previous property. After this change, the routed list is sorted either by (exo:dateModified) if the filter is the draft article list or by (publication:liveDate) if the list has another filter.

2023-11-02 08:11 UTC, rdenarie requested changes, later dismissed

2023-11-02 08:11 UTC, rdenarie commented on services/src/main/java/org/exoplatform/news/storage/jcr/JcrNewsStorage.java
> +    if (node.hasProperty("publication:liveDate") == true) {
```suggestion
    if (node.hasProperty("publication:liveDate")) {
```

2023-11-07 08:39 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-12-19 09:16 UTC, akhanfir commented
I have changed that you ask me, problem is fixed. @rdenarie

2023-12-25 12:50 UTC, ahamdi approved these changes

2023-12-25 12:51 UTC, merged